---
- name: Check for critical updates and install them
  hosts: "{{ hostname }}"
  tasks:
  - win_updates:
      category_names: criticalupdates
    register: wuout
    
  - win_reboot:
    when: wuout.reboot_required
