---
# This playbook installs and enables IIS on Windows hosts

- name: install IIS
  hosts: webservers
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp

  tasks:
  - name: Install Web-Server
    win_feature:
      name: Web-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: win_feature

  - name: Disable Domain firewall
    win_firewall:
      state: disabled

  - name: reboot if installing feature requires it
    win_reboot:
    when: win_feature.reboot_required
    
