---
# This playbook installs and enables IIS on Windows hosts

- name: Install IIS
  hosts: webservers
  gather_facts: false
  vars:
    feature_name: Web-Server
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
  tasks:
#    - include_vars: "{{ myvault }}"
    - name: Install "{{ feature_name ))"
      win_feature:
        name: "{{ feature_name }}"
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: win_feature
    - name: reboot if installing feature requires it
      win_reboot:
      when: win_feature.reboot_required
    - debug: msg="{{ feature_name }}"
